# Generated by Django 4.1.6 on 2023-02-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcadeLoan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('borrower', models.TextField(blank=True, null=True)),
                ('lender', models.TextField(blank=True, null=True)),
                ('borrow_amount', models.TextField(blank=True, null=True)),
                ('borrow_asset', models.TextField(blank=True, null=True)),
                ('loan_duration', models.TextField(blank=True, null=True)),
                ('loan_start', models.DateTimeField(blank=True, null=True)),
                ('loan_end', models.DateTimeField(blank=True, null=True)),
                ('loan_repay_amount', models.TextField(blank=True, null=True)),
                ('nft_asset', models.TextField(blank=True, null=True)),
                ('nft_token_id', models.TextField(blank=True, null=True)),
                ('txhash', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('num_installments', models.IntegerField(blank=True, null=True)),
                ('num_installments_paid', models.IntegerField(blank=True, null=True)),
                ('balance', models.TextField(blank=True, null=True)),
                ('balance_paid', models.TextField(blank=True, null=True)),
                ('late_fees_accrued', models.TextField(blank=True, null=True)),
                ('interest_rate', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NftfiLoan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('borrower', models.TextField(blank=True, null=True)),
                ('lender', models.TextField(blank=True, null=True)),
                ('loan_principal_amount', models.TextField(blank=True, null=True)),
                ('maximum_repayment_amount', models.TextField(blank=True, null=True)),
                ('nft_collateral_id', models.TextField(blank=True, null=True)),
                ('loan_erc20_denomination', models.TextField(blank=True, null=True)),
                ('loan_duration', models.TextField(blank=True, null=True)),
                ('loan_interest_rate_for_duration_in_basis_points', models.IntegerField(blank=True, null=True)),
                ('loan_admin_fee_in_basic_points', models.IntegerField(blank=True, null=True)),
                ('loan_start_time', models.DateTimeField(blank=True, null=True)),
                ('nft_collateral_contract', models.TextField(blank=True, null=True)),
                ('revenue_share_partner', models.TextField(blank=True, null=True)),
                ('revenue_share_in_basis_points', models.TextField(blank=True, null=True)),
                ('referral_fee_in_basis_points', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='X2Y2Liquidation',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('borrower', models.TextField(blank=True, null=True)),
                ('lender', models.TextField(blank=True, null=True)),
                ('borrow_amount', models.TextField(blank=True, null=True)),
                ('nft_asset', models.TextField(blank=True, null=True)),
                ('nft_token_id', models.TextField(blank=True, null=True)),
                ('loan_liquidation_time', models.DateTimeField(blank=True, null=True)),
                ('loan_maturity_time', models.DateTimeField(blank=True, null=True)),
                ('txhash', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='X2Y2Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('borrower', models.TextField(blank=True, null=True)),
                ('lender', models.TextField(blank=True, null=True)),
                ('borrow_amount', models.TextField(blank=True, null=True)),
                ('borrow_asset', models.TextField(blank=True, null=True)),
                ('loan_duration', models.TextField(blank=True, null=True)),
                ('loan_start', models.DateTimeField(blank=True, null=True)),
                ('loan_end', models.DateTimeField(blank=True, null=True)),
                ('loan_repay_amount', models.TextField(blank=True, null=True)),
                ('nft_asset', models.TextField(blank=True, null=True)),
                ('nft_token_id', models.TextField(blank=True, null=True)),
                ('nft_is_collection', models.IntegerField(blank=True, null=True)),
                ('txhash', models.TextField(blank=True, null=True)),
                ('fee', models.TextField(blank=True, null=True)),
                ('nonce', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='X2Y2NonceCancelled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.TextField(blank=True, null=True)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('lender', models.TextField(blank=True, null=True)),
                ('txhash', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='X2Y2Repaid',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_time', models.DateTimeField(blank=True, null=True)),
                ('block_number', models.TextField(blank=True, null=True)),
                ('borrower', models.TextField(blank=True, null=True)),
                ('lender', models.TextField(blank=True, null=True)),
                ('borrow_amount', models.TextField(blank=True, null=True)),
                ('borrow_asset', models.TextField(blank=True, null=True)),
                ('loan_repay_amount', models.TextField(blank=True, null=True)),
                ('nft_asset', models.TextField(blank=True, null=True)),
                ('nft_token_id', models.TextField(blank=True, null=True)),
                ('txhash', models.TextField(blank=True, null=True)),
                ('fee', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
