# Generated by Django 4.1.6 on 2023-02-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenddaoBorrow',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('loan_id', models.IntegerField()),
                ('user', models.TextField()),
                ('on_behalf_of', models.TextField(blank=True, null=True)),
                ('nft_token_id', models.CharField(max_length=20)),
                ('nft_asset', models.CharField(max_length=100)),
                ('transaction_hash', models.TextField(blank=True, null=True)),
                ('reserve', models.TextField(blank=True, null=True)),
                ('referral', models.IntegerField(blank=True, null=True)),
                ('borrow_rate', models.TextField(blank=True, null=True)),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('amount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BenddaoLiquidate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.TextField()),
                ('loan_id', models.IntegerField()),
                ('nft_asset', models.CharField(max_length=100)),
                ('nft_token_id', models.CharField(max_length=20)),
                ('remain_amount', models.TextField()),
                ('repay_amount', models.TextField()),
                ('reserve', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.TextField(blank=True, null=True)),
                ('user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BenddaoRedeem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('block_timestamp', models.DateTimeField(blank=True, null=True)),
                ('borrow_amount', models.TextField()),
                ('borrower', models.TextField()),
                ('fine_amount', models.TextField()),
                ('loan_id', models.IntegerField()),
                ('nft_asset', models.CharField(max_length=100)),
                ('nft_token_id', models.CharField(max_length=20)),
                ('reserve', models.TextField(blank=True, null=True)),
                ('transaction_hash', models.TextField(blank=True, null=True)),
                ('user', models.TextField()),
            ],
        ),
    ]
