# Generated by Django 4.1.6 on 2023-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0002_benddaoborrow_benddaoliquidate_benddaoredeem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arcadeloan",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="benddaoborrow",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="benddaoliquidate",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="benddaoredeem",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="nftfiloan",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="x2y2liquidation",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="x2y2loan",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="x2y2noncecancelled",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="x2y2repaid",
            name="block_number",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
