# Generated by Django 4.1.6 on 2023-02-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0004_nftfiliquidated_nftfirenegotiated_nftfirepaid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="X2Y2Offer",
            fields=[
                ("offer_id", models.TextField(primary_key=True, serialize=False)),
                ("token_id", models.TextField(blank=True, null=True)),
                ("nft_address", models.TextField(blank=True, null=True)),
                ("amount", models.TextField(blank=True, null=True)),
                ("repayment", models.TextField(blank=True, null=True)),
                ("apr", models.IntegerField(blank=True, null=True)),
                ("lender", models.TextField(blank=True, null=True)),
                ("expire_time", models.IntegerField(blank=True, null=True)),
                ("extra", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("erc20_address", models.TextField(blank=True, null=True)),
                ("nonce", models.TextField(blank=True, null=True)),
                ("signature", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("create_time", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
