# Generated by Django 4.1.6 on 2023-02-22 06:30

import aggregators.models.general
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0005_x2y2offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "address",
                    models.CharField(
                        max_length=44,
                        primary_key=True,
                        serialize=False,
                        validators=[aggregators.models.general.validate_address],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NftfiOffers",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField()),
                ("lender", models.CharField(max_length=100)),
                ("lender_nonce", models.TextField(blank=True, null=True)),
                ("borrower", models.TextField(blank=True, null=True)),
                ("referrer", models.TextField(blank=True, null=True)),
                ("loan", models.JSONField()),
                ("signature", models.TextField(blank=True, null=True)),
                ("nftfi", models.JSONField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregators.collection",
                    ),
                ),
            ],
        ),
    ]
