# Generated by Django 4.1.6 on 2023-02-21 09:09
from django.db import migrations, models

import aggregators.models.general


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0005_x2y2offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=44,
                        validators=[aggregators.models.general.validate_address],
                    ),
                ),
            ],
        ),
    ]
