# Generated by Django 4.1.6 on 2023-02-22 06:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0006_collection_nftfioffers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NftfiOffers",
            new_name="NftfiOffer",
        ),
    ]
