# Generated by Django 4.1.6 on 2023-02-22 21:39

import aggregators.models.general
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0009_alter_nftfioffer_apr_alter_x2y2offer_apr"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionOffer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("nftfi", "nftfi"),
                            ("x2y2", "x2y2"),
                            ("arcade", "arcade"),
                            ("bendao", "bendao"),
                        ],
                        max_length=15,
                    ),
                ),
                ("apr", models.FloatField()),
                ("amount", models.CharField(max_length=25)),
                ("repayment", models.CharField(max_length=25)),
                ("expire_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                (
                    "erc20_address",
                    models.CharField(
                        max_length=44,
                        validators=[aggregators.models.general.validate_address],
                    ),
                ),
                (
                    "lender",
                    models.CharField(
                        max_length=44,
                        validators=[aggregators.models.general.validate_address],
                    ),
                ),
                ("create_time", models.DateTimeField()),
                ("nonce", models.TextField(blank=True, null=True)),
                ("signature", models.TextField(blank=True, null=True)),
                ("x2y2_metadata", models.JSONField(blank=True, null=True)),
                ("nftfi_metadata", models.JSONField(blank=True, null=True)),
                ("arcade_metadata", models.JSONField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aggregators.collection",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="x2y2offer",
            name="collection",
        ),
        migrations.DeleteModel(
            name="NftfiOffer",
        ),
        migrations.DeleteModel(
            name="X2Y2Offer",
        ),
        migrations.AddConstraint(
            model_name="collectionoffer",
            constraint=models.UniqueConstraint(
                fields=("id", "marketplace"), name="unique_id_and_marketplace"
            ),
        ),
    ]
