# Generated by Django 4.1.6 on 2023-02-23 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0009_remove_arcadeloanclaimed_amount_and_more"),
        ("aggregators", "0010_collectionoffer_remove_x2y2offer_collection_and_more"),
    ]

    operations = []
