# Generated by Django 4.1.6 on 2023-02-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0011_merge_20230223_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyMetadata",
            fields=[
                (
                    "address",
                    models.CharField(max_length=44, primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(blank=True, max_length=15, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("decimals", models.IntegerField(blank=True, null=True)),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ethereum", "ethereum"),
                            ("solana", "solana"),
                            ("binance_smart_chain", "binance_smart_chain"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("coingecko", "coingecko"), ("notabene", "notabene")],
                        default="notabene",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
