# Generated by Django 4.1.6 on 2023-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aggregators", "0014_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="immutable_token_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
