repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3.9
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [ python ]
#        args:
#          [
#            "-rn", # Only display messages
#            "-sn", # Don't display the score
#            "--rcfile=.pylintrc", # Link to your config file
#            "--load-plugins=pylint.extensions.docparams", # Load an extension
#          ]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        args: ["--with", "dev", "--without-hashes",  "-f", "requirements.txt", "-o", "requirements.txt"]
