version: '3.3'
services:

  redis:
    container_name: "${REDIS_HOST_NAME}"
    image: "bitnami/redis:6.0.9"
#    networks:
#      - "django_network_local"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "./redis_data:/data"
    environment:
      - "REDIS_PORT=${REDIS_PORT}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "ALLOW_EMPTY_PASSWORD=no"
    sysctls:
      net.core.somaxconn: 1024
    restart: always
    command: "/opt/bitnami/scripts/redis/run.sh --maxmemory 300mb"
