NFTFI = "nftfi"
X2Y2 = "x2y2"
ARCADE = "arcade"
BENDDAO = "bendao"

MARKETPLACES = (
    (NFTFI, NFTFI),
    (X2Y2, X2Y2),
    (ARCADE, ARCADE),
    (BENDDAO, BENDDAO),
)


COINGECKO = "coingecko"
NOTABENE = "notabene"
CURRENCY_METADATA_SOURCE = ((COINGECKO, COINGECKO), (NOTABENE, NOTABENE))

ETHEREUM = "ethereum"
SOLANA = "solana"
BINANCE = "binance_smart_chain"
SUPPORTED_NETWORKS = [ETHEREUM]
NETWORKS_CHOICES = ((net, net) for net in SUPPORTED_NETWORKS)


SNOWGNESIS_LISTING_PROTOCOLS = {
    1: NFTFI,
    10: NFTFI,
    30: ARCADE,
}
