version: '3.3'
services:
  db:
    image: kartoza/postgis:13-3.1
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASS: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      ALLOW_IP_RANGE: 0.0.0.0/0

    networks:
      - "db_network"

networks:
  db_network:
    external: True
