run_postgres:
	DB_PORT=5431 docker compose --env-file ../nft_loans/configs/.env.dev.local up db_postgres

run_postgres_bg:
	DB_PORT=5431 docker compose --env-file ../nft_loans/configs/.env.dev.local up db_postgres -d
